/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'streamline-ultimate:house-4-bold',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'system-settings',
    path: '/system-settings',
    component: 'layout.base',
    meta: {
      title: 'system-settings',
      i18nKey: 'route.system-settings',
      icon: 'ic:round-settings',
      roles: ['ROLE_SUPER_ADMIN'],
      order: 10
    },
    children: [
      {
        name: 'system-settings_message-management',
        path: '/system-settings/message-management',
        meta: {
          title: 'system-settings_message-management',
          i18nKey: 'route.system-settings_message-management',
          icon: 'mynaui:message-dots-solid'
        },
        children: [
          {
            name: 'system-settings_message-management_notification-configuration',
            path: '/system-settings/message-management/notification-configuration',
            component: 'view.system-settings_message-management_notification-configuration',
            meta: {
              title: 'system-settings_message-management_notification-configuration',
              i18nKey: 'route.system-settings_message-management_notification-configuration'
            }
          },
          {
            name: 'system-settings_message-management_template-management',
            path: '/system-settings/message-management/template-management',
            component: 'view.system-settings_message-management_template-management',
            meta: {
              title: 'system-settings_message-management_template-management',
              i18nKey: 'route.system-settings_message-management_template-management',
              icon: 'material-symbols:android-messages'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center',
      icon: 'ix:user-management-settings-filled',
      order: 9,
      roles: ['ROLE_USER', 'ROLE_SUPER_ADMIN']
    },
    children: [
      {
        name: 'user-center_buy-detail',
        path: '/user-center/buy-detail/:id',
        component: 'view.user-center_buy-detail',
        props: true,
        meta: {
          title: 'user-center_buy-detail',
          i18nKey: 'route.user-center_buy-detail',
          hideInMenu: true,
          activeMenu: 'user-center_user-list',
          roles: ['ROLE_USER', 'ROLE_SUPER_ADMIN']
        }
      },
      {
        name: 'user-center_user-list',
        path: '/user-center/user-list',
        component: 'view.user-center_user-list',
        meta: {
          title: 'user-center_user-list',
          i18nKey: 'route.user-center_user-list',
          icon: 'mdi:text-account',
          order: 1,
          roles: ['ROLE_USER', 'ROLE_SUPER_ADMIN']
        }
      }
    ]
  }
];
